name: Deploy On Push
on: [push]

env:
  AZURE_WEBAPP_NAME: Jasono's Portfolio # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "" # set this to the path to your web app project, defaults to the repository root
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test  --if-present
      - name: "Deploy to Github Pages"
        uses: actions/deploy-pages@v2
        # with:
        #   app-name: ${{ env.AZURE_WEBAPP_NAME }}
        #   publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        #   package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
